spring:
  application:
    name: shopping-monitor
  security: # 配置登录用户名和密码
    user:
      name: coca
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 8501
